---
title: "FigS3"
author: "Haoran Xu"
date: "2024/09/13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Clean workspace
rm(list=ls()) 
# Load setting and functions
library(ggplot2)
library(Rmisc)
library(ggpubr)
library(reshape2)
library(tidyr)
library(dplyr)
library(rstatix)
library(VennDiagram)
options(scipen=999)
```

## FigS3 A-B

```{R}
# read table
design = read.table("dataForFig3S_design.txt", header=T, row.names=1, sep="\t") 
asvtab = read.table("dataForFigS3_GenusTable.txt", header=T, row.names=1, quote = "", sep="\t", comment.char="") 

NegativeList = c("Tolumonas", "Pleomorphomonas", "Exiguobacterium", "Burkholderia", "Paenibacillus")
PositiveList = c("Spirochaeta", "Chitinispirillum", "Geothrix", "Sideroxydans", "Roseateles", "Anaeromyxobacter", "Piscinibacter")

# Correlation Genus
CorrelationGenus = asvtab[row.names(asvtab) %in% c("Tolumonas", "Pleomorphomonas", "Exiguobacterium", "Burkholderia", "Paenibacillus", "Spirochaeta", "Chitinispirillum", "Geothrix", "Sideroxydans", "Roseateles", "Anaeromyxobacter", "Piscinibacter"),]

m = 0.2

norm = t(t(asvtab)/colSums(asvtab,na=T)*100)
filtered <- t(norm[rowMeans(norm) > m, ])
filtered = as.data.frame(filtered[,colnames(filtered) != "Unassigned"])

# Enriched or depeleted
grp = design[, "group", drop=F]
mat_t2 = merge(grp, filtered, by="row.names")[,-1]
mat_mean = as.data.frame(t(aggregate(mat_t2[,-1], by=mat_t2[1], FUN=mean))) # mean
colnames(mat_mean) = mat_mean[1,]
mat_mean = mat_mean[-1,]
comparison <- mat_mean %>%
  mutate(
    compare_d10 = if_else(`d10RtBj` > `NpRtBj`, "MutantEnriched", "MutantDepeleted"),
    compare_d17 = if_else(`d17RtBj` > `NpRtBj`, "MutantEnriched", "MutantDepeleted"),
    compare_d14 = if_else(`d14RtBj` > `NpRtBj`, "MutantEnriched", "MutantDepeleted"),
    compare_d53 = if_else(`d53RtBj` > `NpRtBj`, "MutantEnriched", "MutantDepeleted")
  )


# Wilcoxon
filtered$SampleID = rownames(filtered)
design$SampleID = rownames(design)
# NegativeList %in% rownames(filtered)
# PositiveList %in% rownames(filtered)
asvtab2 = merge(filtered, design[c("SampleID", "group")], by = "SampleID", all = T)
asvtab3 <- melt(
  asvtab2,
  id.vars = c("SampleID", "group"), # 保留这些列
  variable.name = "Bacteria",       # 新列名，存放细菌属
  value.name = "Abundance"          # 新列名，存放丰度值
)
asvtab3$group2 = paste(asvtab3$group, asvtab3$Bacteria, sep = "__")
GenusList = unique(asvtab3$Bacteria)
comparisons_list <- lapply(GenusList, function(bac) {
  list(
    c(paste0("NpRtBj__", bac), paste0("d14RtBj__", bac)),  # Np vs d14
    c(paste0("NpRtBj__", bac), paste0("d17RtBj__", bac)),  # Np vs d17
    c(paste0("NpRtBj__", bac), paste0("d10RtBj__", bac)),  # Np vs d14
    c(paste0("NpRtBj__", bac), paste0("d53RtBj__", bac))  # Np vs d17
  )
})
comparisons_list <- do.call(c, comparisons_list)

results_wilcoxon <- data.frame(
  Comparison = character(),
  W = numeric(),
  P.value = numeric(),
  stringsAsFactors = FALSE
)

for (i in 1:length(comparisons_list)){
  Genus1 <- comparisons_list[[i]][1]
  Genus2 <- comparisons_list[[i]][2]
  data1 <- subset(asvtab3, `group2` == Genus1)$Abundance
  data2 <- subset(asvtab3, `group2` == Genus2)$Abundance
  test_result <- wilcox.test(data1, data2)
    results_wilcoxon <- rbind(results_wilcoxon, data.frame(
  Comparison = paste(Genus1, "vs", Genus2),
  W = test_result$statistic,
  P.value = test_result$p.value
  ))
}

results_wilcoxon <- results_wilcoxon %>% separate(Comparison, into = c("Group1", "Group2"), sep = " vs ")
results_wilcoxon <- results_wilcoxon %>% separate(Group2, into = c("Mutant", "Bacteria"), sep = "__")

results_wilcoxon <- results_wilcoxon %>%
  group_by(Mutant) %>%
  adjust_pvalue(method = "BH", p.col = "P.value") 
  
results_wilcoxon <- results_wilcoxon %>%
  mutate(Sig = ifelse(P.value.adj < 0.05, "Sig", "NoSig"))


comparison$d10 = "d10RtBj"
comparison$d14 = "d14RtBj"
comparison$d17 = "d17RtBj"
comparison$d53 = "d53RtBj"
comparison$Bacteria = rownames(comparison)

d10Table = comparison[c("d10RtBj","NpRtBj","compare_d10","d10","Bacteria")]
d14Table = comparison[c("d17RtBj","NpRtBj","compare_d17","d17","Bacteria")]
d17Table = comparison[c("d14RtBj","NpRtBj","compare_d14","d14","Bacteria")]
d53Table = comparison[c("d53RtBj","NpRtBj","compare_d53","d53","Bacteria")]

colnames(d10Table) = c("MutantAbundance","NpAbundance","compare","Mutant","Bacteria")
colnames(d14Table) = c("MutantAbundance","NpAbundance","compare","Mutant","Bacteria")
colnames(d17Table) = c("MutantAbundance","NpAbundance","compare","Mutant","Bacteria")
colnames(d53Table) = c("MutantAbundance","NpAbundance","compare","Mutant","Bacteria")

resultTable = rbind(d10Table,d14Table,d17Table,d53Table)
resultTable = merge(resultTable, results_wilcoxon[c("Mutant","Bacteria","P.value","P.value.adj","Sig")], by = c("Mutant","Bacteria"), all = T)
 

# Enriched data 
# A d10GeneEnriched; B d17; C d14; D d53; E Tiller(-) Bac
A <- resultTable %>% filter(Mutant == "d10RtBj", compare == "MutantDepeleted", Sig == "Sig") %>% pull(Bacteria)
B <- resultTable %>% filter(Mutant == "d17RtBj", compare == "MutantDepeleted", Sig == "Sig") %>% pull(Bacteria)
C <- resultTable %>% filter(Mutant == "d14RtBj", compare == "MutantDepeleted", Sig == "Sig") %>% pull(Bacteria)
D <- resultTable %>% filter(Mutant == "d53RtBj", compare == "MutantDepeleted", Sig == "Sig") %>% pull(Bacteria)
E <- c("Tolumonas", "Pleomorphomonas", "Exiguobacterium", "Burkholderia", "Paenibacillus")
p <- venn.diagram(
  x = list(d10=A, d17=B, d14=C, d53=D, TillerNegative=E),
  filename = NULL, fill = c("#63b2ee","#76da91","#f8cb7f","#f89588","#9192ab"), alpha = 0.70, main = "Tiller Negative Genus")
#ggsave("FigS3A.png",p, width = 3, height = 3)
ggsave("FigS3A.pdf",p, width = 3, height = 3)

# Depleted data 
# A d10GeneDepleted; B d17; C d14; D d53; E Tiller(-) Bac
A <- resultTable %>% filter(Mutant == "d10RtBj", compare == "MutantEnriched", Sig == "Sig") %>% pull(Bacteria)
B <- resultTable %>% filter(Mutant == "d17RtBj", compare == "MutantEnriched", Sig == "Sig") %>% pull(Bacteria)
C <- resultTable %>% filter(Mutant == "d14RtBj", compare == "MutantEnriched", Sig == "Sig") %>% pull(Bacteria)
D <- resultTable %>% filter(Mutant == "d53RtBj", compare == "MutantEnriched", Sig == "Sig") %>% pull(Bacteria)
E <- c("Spirochaeta", "Chitinispirillum", "Geothrix", "Sideroxydans", "Roseateles", "Anaeromyxobacter", "Piscinibacter")
p <- venn.diagram(
  x = list(d10=A, d17=B, d14=C, d53=D, TillerPositive=E),
  filename = NULL, fill = c("#63b2ee","#76da91","#f8cb7f","#f89588","#9192ab"), alpha = 0.70, main = "Tiller Positive Genus")
#ggsave("FigS3B.png",p, width = 3, height = 3)
ggsave("FigS3B.pdf",p, width = 3, height = 3)

```



## FigS3 C-E. 

```{r}
# read genus table
GenusTable = read.table("dataForFigS3_GenusTable.txt", header=T, row.names=1, quote = "", sep="\t", comment.char="") 
norm = t(t(GenusTable)/colSums(GenusTable,na=T)*100)

# 4 correlation genus
CorrelationGenus = norm[row.names(norm) %in% c("Pleomorphomonas", "Exiguobacterium", "Roseateles", "Piscinibacter"),]

# experimental design table
design = read.table("dataForFig3S_design.txt", header=T, row.names=1, sep="\t")
design$SampleName = rownames(design)

CorGenus = as.data.frame(t(CorrelationGenus))
CorGenus$SampleName = rownames(CorGenus)
CorGenus = merge(CorGenus, design[,c("group","SampleName")], by = "SampleName")
phenotypeList = c("Pleomorphomonas", "Exiguobacterium", "Roseateles", "Piscinibacter")

for (phenotype in phenotypeList) {
  #calculate plot data
  ForPlot <- summarySE(CorGenus, measurevar = phenotype, groupvars ="group")
  #statistics
  ForSig = CorGenus
  ForSig = ForSig[, c("group", phenotype)]
  ForSig$group = factor(ForSig$group, levels = c("NpRtBj", "d10RtBj", "d17RtBj", "d14RtBj", "d53RtBj"))
  colnames(ForSig)[2] = "y"
  WilcoxtestResult = compare_means(y ~ group, data = ForSig, method = "wilcox.test", paired = F,)
  colnames(ForSig)[2] = phenotype
  WilcoxtestResult = as.data.frame(WilcoxtestResult)
  WilcoxtestResult = WilcoxtestResult[c(1:4),]
  WilcoxtestResult$padjFDR = p.adjust(WilcoxtestResult$p, method = "fdr", n = length(WilcoxtestResult$p))
  
  WilcoxtestResult = WilcoxtestResult[, c("group2", "method", "p", "padjFDR")]
  SigTableFinal = WilcoxtestResult
  for (padjmethod in c("p", "padjFDR")){
    asterisk = paste(padjmethod, "Asterisk", sep = "")
    for (m in 1:length(SigTableFinal[,1])){
      ifelse (SigTableFinal[[padjmethod]][m] < 0.001,
              SigTableFinal[[asterisk]][m] <- "***",
              ifelse (SigTableFinal[[padjmethod]][m] < 0.01,
                      SigTableFinal[[asterisk]][m] <- "**",
                      ifelse (SigTableFinal[[padjmethod]][m] < 0.05,
                              SigTableFinal[[asterisk]][m] <- "*", SigTableFinal[[asterisk]][m] <- "")))
    }
  }
  SigTableFinal = merge(ForPlot[,c("group","N", phenotype)], SigTableFinal, by.x = "group", by.y = "group2", all = T)
  #write.table(SigTableFinal, file=paste0("StatisticsResultForFig2E_", phenotype, ".csv"),append = F, quote = F, sep = ",", row.names = F, col.names = T)
  padjmethod = "padjFDRAsterisk"
  SigTableFinal$asterisk = SigTableFinal[[padjmethod]]
  #prepare data for plot
  ForPlot = merge(ForPlot, SigTableFinal[,c("group", "asterisk")], all = T)
  ForPlot$max = (ForPlot[[phenotype]] + ForPlot$se)*1.2
  #save plot
  p = ggplot(data = ForPlot, aes(x = group, y = .data[[phenotype]], fill = group)) +
    geom_boxplot(data = ForSig, aes(x = group, y = .data[[phenotype]], color = group), alpha=0.75, outlier.alpha=0, size=0.7, width=0.5) +
    geom_jitter(data = ForSig, aes(x = group, y = .data[[phenotype]], color = group), size=0.5, alpha=0.7, width = 0.2, height = 0.02)+theme(legend.position="none") +
    geom_text(aes(x = group, y = max, label = asterisk)) +
    scale_fill_manual(values = c("#888888", "#bd6b08", "#bd6b08", "#00686b", "#00686b")) +
    scale_color_manual(values = c("#888888", "#bd6b08", "#bd6b08", "#00686b", "#00686b")) +
    xlab("") +
    theme(
    plot.background = element_rect(fill = "#FFFFFF"), 
    panel.background = element_blank(), 
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_blank(), 
    panel.grid.minor.x = element_blank(), 
    panel.grid.minor.y = element_blank(),
    panel.border = element_blank(), 
    axis.title = element_text(size = 8),  
    axis.text = element_text(size = 8, vjust = 1, hjust = 1, colour = "#000000"), 
    axis.line = element_line(colour = "#000000"),
    legend.title = element_blank(),
    legend.key = element_rect(fill = "#FFFFFF"),
    legend.position = "none"
    )
  
  p = p + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
  
  ggsave(p, filename = paste0("FigS3_", phenotype, ".pdf"), width = 2.5, height = 2)
  #ggsave(p, filename = paste0("FigS3_", phenotype, ".pdf"), width = 2.4, height = 2.2)
}


```
